### ISSUE TITLE
Built-in runit cookbook shouldn't use upstart under docker

### ISSUE THREAD

**Issue by coderanger** [chef/omnibus-chef-server#93]
Docker has no upstart, it should try to fall back on old schoolz.

**Comment by smith** [comment]
Chef server 12 uses this recipe to determine how to run runit: https://github.com/opscode-cookbooks/enterprise-chef-common/blob/master/recipes/runit.rb

@coderanger may have something that gets us toward a solution in this provider: https://github.com/poise/poise-service-runit/blob/master/lib/poise_service/providers/runit.rb#L38

Using something like the init in the Passenger Base Image might be a good option too: https://github.com/phusion/baseimage-docker/blob/master/image/bin/my_init

I'm going to close this, since it won't be added (by Chef Software, Inc., at least) to open source Chef server 11, but if anybody is interested, they should open an issue on [chef/chef-server](https://github.com/chef/chef-server) and it can be tracked there. Thanks!
